dishes/urls.py
from django.urls import path

from . import views

app_name='dishes'


urlpatterns = [
    path('', views.index, name='index'),
    path('dishes', views.leaderboard, name='leaderboard'),
    path('add-dish', views.dishAdd, name='dishAdd'),
    path('dish_details/<int:dish_Id>', views.dish_details, name='dish_details'),
    # path('user-vote/<int:dish_Id>', views.vote, name='vote'),
    # path('admin/products_details/<int:dish_Id>', views.dish_details, name='dish_details'),
]

foodcourt/urls.py
from django.contrib import admin
from django.urls import include,path
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('', include('dishes.urls',)),
    path('', include('users.urls',)),
    path('admin/', admin.site.urls),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path

from . import views

app_name='users'


urlpatterns = [
    path('login/', views.f_login, name='f_login'),
    path('sign_up/', views.f_sign_up, name='f_sign_up'),
    path('logout/',views.logoutUser,name='logout')
    
]

templates/dish_add.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>Document</title>
    <!-- CSS only -->
<link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">

</head>
<body>

    <div style="margin: 50px; padding: 10px; border: 2px solid orange; border-radius: 5px;">
        <form method="post" enctype="multipart/form-data">
            {% csrf_token %}
            <div class="row">
              <div class="col-7">
                <div class="form-group">
                  <label for="dName">Dish Name</label>
                  <input type="text" class="form-control" name="dName" id="dName" placeholder="Poha">
                </div> <br>
              </div>
              <div class="col-5">
                <div class="form-group">
                  <label for="dName">Dish Price</label>
                  <input type="number" class="form-control" name="dPrice" id="dPrice" placeholder="">
                </div> <br>
              </div>
            </div>

              <div class="form-group">
                <label for="dDescription">Dish Description</label>
                <textarea class="form-control" name="dDescription" id="dDescription" rows="3"></textarea>
              </div> <br>
              <div class="form-group">
                <label for="dIngredients">Dish Ingredients</label>
                <textarea class="form-control" name="dIngredients" id="dIngredients" rows="3"></textarea>
              </div> <br>
              <div class="row">

                <div class="col" style="padding-left: 80px;">
                    <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="dtype" id="inlineRadio1" value="Veg">
                        <label class="form-check-label" for="inlineRadio1">Veg</label>
                      </div>
                      <div class="form-check form-check-inline">
                        <input class="form-check-input" type="radio" name="dtype" id="inlineRadio2" value="nonVeg">
                        <label class="form-check-label" for="inlineRadio2">nonVeg</label>
                      </div>
                </div>
                <div class="col">
                    <div class="form-group">
                        <label for="dPhoto">Upload Dish Photo</label>
                        <input type="file" class="form-control-file" name="dPhoto" id="dPhoto">
                      </div>
                </div>
              </div> <br>
              <div class="row">
                <div class="col-5"></div>
                <div class="col-1">
                    <button type="submit" class="btn btn-primary">Add</button>
                </div>
              </div>
              
          </form>

          <div class="row">
            <div class="col-6"></div>
            <div class="col-6">
                {% if messages %}
                {% for message in messages %}
                <div class="container-fluid p-0">
                  <div class="alert {{ message.tags }} alert-dismissible fade show" role="alert" >
                    <!-- <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                      <span aria-hidden="True">&times;</span>
                    </button> -->
                    {{ message }}
                    <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                        <span aria-hidden="true">&times;</span>
                      </button>
                  </div>
                </div>
                {% endfor %}
            {% endif %}
            </div>
          </div>
          
    </div>

      <!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/dishes.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <!-- CSS only -->
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <title>Document</title>
</head>
<body>
    
    <div class="container" style="margin: 50px;">

        <!-- Todays  -->
        <!-- <div class="row">
            <div class="col-1"></div>
            <div class="col-4">
                <h1 class="text-center mt-5">Leaderboard</h1>
                <h5 class="text-center lb mb-5">Today's Top Dishes</h5>
            </div>
            <div class="col-4"></div>
        </div>
        <div class="row"></div> -->


        <div class="col text-left">
            <div class="row"><div class="col-4"><h1 class="mt-3">
                <svg xmlns="http://www.w3.org/2000/svg" width="35" height="35" fill="currentColor" class="bi bi-clipboard-data" viewBox="0 0 16 16">
                    <path d="M4 11a1 1 0 1 1 2 0v1a1 1 0 1 1-2 0v-1zm6-4a1 1 0 1 1 2 0v5a1 1 0 1 1-2 0V7zM7 9a1 1 0 0 1 2 0v3a1 1 0 1 1-2 0V9z"/>
                    <path d="M4 1.5H3a2 2 0 0 0-2 2V14a2 2 0 0 0 2 2h10a2 2 0 0 0 2-2V3.5a2 2 0 0 0-2-2h-1v1h1a1 1 0 0 1 1 1V14a1 1 0 0 1-1 1H3a1 1 0 0 1-1-1V3.5a1 1 0 0 1 1-1h1v-1z"/>
                    <path d="M9.5 1a.5.5 0 0 1 .5.5v1a.5.5 0 0 1-.5.5h-3a.5.5 0 0 1-.5-.5v-1a.5.5 0 0 1 .5-.5h3zm-3-1A1.5 1.5 0 0 0 5 1.5v1A1.5 1.5 0 0 0 6.5 4h3A1.5 1.5 0 0 0 11 2.5v-1A1.5 1.5 0 0 0 9.5 0h-3z"/>
                  </svg>
                Leaderboard</h1>
                <hr style="height: 2px; color: orange; margin: 3px; width: 20vw;">
            </div></div>
            <div class="row"><div class="col-4"><h5 class="lb">Today's Top Dishes</h5></div></div>
            <hr style="height: 2px; color: orange; margin: 3px; width: 15vw;">
            <div class="row pt-3" style="">
                {% for dish in top_dishes %}
                <div class="col mb-3">
                    <a href="/dish_details/{{ dish.dish_Id }}" style="text-decoration: none; color: inherit;">
                    <div class="card" style="width: 18rem;">
                        <!-- <img src="..." class="card-img-top" alt="..."> -->
                        <img src="{{ BASIC_DIR }}/uploads/{{dish.d_Photo}}" alt="dish_img" style="width: 500px; height: 300px;"  class="img-fluid p-2">
                        <div class="card-body">
                          <div class="col">
                            <div class="row"><h5 class="text-center" style=" white-space: nowrap "> <b>{{dish.d_Name}}</b></h5></div>
                            <hr style="height: 2px; color: orange; margin: 3px;">
                            <div class="row">
                                <div class="col text-center">₹{{dish.d_Price}}</div>
                                <div class="col">Votes: {{dish.d_Votes}}</div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                </div>
                
                {% endfor %}
            </div>

            <div class="row"><div class="col-4"><h5 class="lb">Tomorrow's Top Dishes</h5></div></div>
            <hr style="height: 2px; color: orange; margin: 3px; width: 15vw;">
            <div class="row pt-3" style="">
                {% for dish in top_dishes %}
                <div class="col mb-3">
                    <a href="/dish_details/{{ dish.dish_Id }}" style="text-decoration: none; color: inherit;">
                    <div class="card" style="width: 18rem;">
                        <!-- <img src="..." class="card-img-top" alt="..."> -->
                        <img src="{{ BASIC_DIR }}/uploads/{{dish.d_Photo}}" alt="dish_img" style="width: 500px; height: 300px;"  class="img-fluid p-2">
                        <div class="card-body">
                          <div class="col">
                            <div class="row"><h5 class="text-center" style=" white-space: nowrap "> <b>{{dish.d_Name}}</b></h5></div>
                            <hr style="height: 2px; color: orange; margin: 3px;">
                            <div class="row">
                                <div class="col text-center">₹{{dish.d_Price}}</div>
                                <div class="col">Votes: {{dish.d_Votes}}</div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                </div>
                
                {% endfor %}
            </div>

            <div class="row"><div class="col-4"><h5 class="lb">All Dishes</h5></div></div>
            <hr style="height: 2px; color: orange; margin: 3px; width: 15vw;">
            <div class="row pt-3" style="">
                {% for dish in dish %}
                <div class="col mb-3">
                    <a href="/dish_details/{{ dish.dish_Id }}" style="text-decoration: none; color: inherit;">
                    <div class="card" style="width: 18rem;">
                        <!-- <img src="..." class="card-img-top" alt="..."> -->
                        <img src="{{ BASIC_DIR }}/uploads/{{dish.d_Photo}}" alt="dish_img" style="width: 500px; height: 300px;"  class="img-fluid p-2">
                        <div class="card-body">
                          <div class="col">
                            <div class="row"><h5 class="text-center" style=" white-space: nowrap "> <b>{{dish.d_Name}}</b></h5></div>
                            <hr style="height: 2px; color: orange; margin: 3px;">
                            <div class="row">
                                <div class="col text-center">₹{{dish.d_Price}}</div>
                                <div class="col"></div>
                            </div>
                          </div>
                        </div>
                      </div>
                    </a>
                </div>
                
                {% endfor %}
            </div>
        </div>

    </div>

<!-- JavaScript Bundle with Popper -->
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous"></script>
</body>
</html>

templates/index.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">

    {% load static %}

    <title>Food Court</title>
    <link rel="icon" href="final32.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/final32.png' %}" type="image/x-icon">

</head>

<body>

    <style>
        body {
            background-image: none;
            overflow-y:scroll!important;
        
        }


        img {
                scale:1.5;
            }
        .btn{
        width: 16rem;
        background-color: var(--success);
        border-radius: 16px;
        color: white;
        font-family: 'Poppins',cursive;
      }
.logo{
    font-size: 4rem;
}

span {
            font-style: italic;
            font-weight: 100;



        }  h1{
    font-weight: 800;
    font-size: 4rem;
      }


      p{
        margin-top: 3rem;
        font-size: 1.5rem;
        padding: 6rem;
      }
      .btn{
        width: 20rem;
        height: 3rem;
      }
      @media only screen and (max-width: 700px) {
           

            
            
          
        img {
            scale: 1.4;
        }

      

      h1{
    font-weight: 800;
    font-size: 40px;
      }

        .logo{
            font-size: 40px;
         }
    
      .btn{
        width: 16rem;
        background-color: var(--success);
        border-radius: 16px;
        color: white;
        font-family: 'Poppins',cursive;
      }

      
      p{
        margin-top: 0;
        font-size: 1rem;
        padding:0;
      }
        }
    </style>



    <div class="container-fluid d-block">
        <div class="loader">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        <div class="row mt-5">
            <div class="col-lg-7">
                <img src="{% static 'img/banner-img.png' %}" alt="" class="img-fluid mt-3">

            </div>
            <div class="col-lg-5 mt-5">
                <div class="text-center logo  mt-5">
                    <span>FOOD</span>

                        <div style="display: inline-block"> <h1>COURT</h1></div>

                  </div>
<div class="text-center mt-4 p-2" >


<p style="color: var(--light-black);">Democratising what you eat ;)
    Vote now for your favourite dishes!</p>

</div>
<div class="text-center d-flex  flex-column justify-content-center align-items-center mt-4">
<a href="{% url 'users:f_login' %}" class="home">  <button class="btn mt-5 hover-filled-opacity">Log In</button></a>
  

<a href="{% url 'dishes:leaderboard' %}" class="home" ><button class="btn mt-5" style="color: black; background-color:white!important"   ><b>Skip</b>   </button></a>


</div>

            </div>
        </div>

    </div>


















    <!-------javascript bundle----->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>

    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>

<script src="{% static 'js/preloader.js' %}"></script>
</body>

</html>

templates/login.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>FOOD COURT</title>
    <link rel="icon" href="final32.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style.css' %}">
    <link rel="icon" href="{% static 'img/final32.png' %}" type="image/x-icon">

</head>

<body>

    <style>
        body {
            background-image: none;
          
        
           overflow: hidden;
           overflow-y: scroll;
        
        }


        img {
            scale: 1.2;
        }

        .btn {
            width: 16rem;
            background-color: var(--success);
            border-radius: 16px;
            color: white;
            font-family: 'Poppins', cursive;
        }

        .logo {
            font-size: 4rem;
        }

        span {
            font-style: italic;
            font-weight: 100;



        }

        h1 {
            font-weight: 800;
            font-size: 4rem;
        }


        p {
            margin-top: 0rem;
            font-size: 1.5rem;
            padding: 2rem;
        }

        .btn {
            width: 20rem;
            height: 3rem;
        }
        
i{
    position: absolute;
    top: 5rem;
    left: 6rem;
}

a {
  text-decoration: none !important;
 
}
        @media only screen and (max-width: 700px) {





            img {
                display: none;
            }



            h1 {
                font-weight: 800;
                font-size: 40px;
            }

            .logo {
                font-size: 40px;
            }

            .btn {
                width: 16rem;
                background-color: var(--success);
                border-radius: 16px;
                color: white;
                font-family: 'Poppins', cursive;
            }


            p {
                margin-top: 2rem;
                font-size: 1rem;
                padding: 0;
            }
            i{
           margin: 0;
           position: absolute;
           top: 4rem ;
           left: 2rem; 

        }
        h5{
            font-size: 0.9rem;
        }
        }
    </style>



    <div class="container-fluid d-block">
        <div class="loader">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        <a value="Previous Page" onClick="javascript:history.go(-1);" class="back">  <i class="fa-solid fa-angles-left float-start fa-lg "></i></a>
      
       
        
        <div class="row mt-5">
           
            <div class="col-lg-7 mt-5">
            
               
               
                <div class="  logo  mt-5">
                    
                 <div class="text-center">
                   
                 
                  <span >FOOD</span>

                    <div style="display: inline-block">
                        <h1 >COURT</h1>
                    </div>
                    <p style="color:var(--light-black)">Tired of the same old thing? let your stomach decide what you
                        eat</p>
                    </div>
                </div>
                <div class="text-center mt-4 p-2">


                    <h3 style="font-weight: 800;" class="mt-5 mx-5">Login now & eat what you vote for!</h2>

                </div>
                <div class="text-center d-flex  flex-column  align-items-center mt-2">
                    <form class="my-3" method="post">
                        {% csrf_token %}
                        <div class="form-group my-3 ">
                            <label for="text1" class="float-start my-3">E-mail Address:</label>
                            <input id="text1" name="email_address" type="text" class="form-control">
                        </div>
                        <div class="form-group my-5">
                            <label for="text" class="float-start my-3">Password</label>
                            <input id="text" name="password" type="text" class="no-outline form-control">
                        </div>
                        <div class="form-group my-3">
                            <button name="submit" type="submit" class="btn btn-primary">Submit</button>
                        </div>
                    </form>
<h5 class="text-center mt-1" style="color: var(--light-black);">Dont have an account <a href="{% url 'users:f_sign_up' %}" style="color:black ;"><u>Sign Up</u></a> now!</h5>
                </div>

            </div>

            <div class="sign up col-lg-5">
                <img src="{% static 'img/login.png' %}" alt="" class="img-fluid mt-3">

            </div>
        </div>

    </div>


















    <!-------javascript bundle----->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>

    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="{% static 'js/preloader.js' %}"></script>

</body>

</html>

templates/menu1.html
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    {% load static %}
    <title>FOOD COURT:{{number.no}},{{dish_name}}</title>
    <link rel="icon" href="final32.png" type="image/x-icon">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css"
        integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.2.0/css/all.min.css"
        integrity="sha512-xh6O/CkQoPOWDdYTDqeRdPCVd1SpvCA9XXcUnZS2FmJNp1coAFzvtCN9BmamE+4aHK8yyUHUSCcJHgXloTyT2A=="
        crossorigin="anonymous" referrerpolicy="no-referrer" />
    <link rel="stylesheet" href="{% static 'css/style2.css' %}">
    <style>

    </style>
</head>


<body>

    <div class="container-fluid g-0 xs sm d-lg-none d-md-none d-xl-none">
        <div class="loader">
            <span></span>
            <span></span>
            <span></span>
            <span></span>
          </div>
        <div class=" d-flex flex-column  ">
            <a href="leaderboard.html"><button class="" id="back"><i class="fa-solid fa-2x fa-chevron-left"></i>
            </button></a>
            <img src="{% static 'img/i1.jpg' %}" alt="" srcset="" class="scale-down-top">
            <div class="card fadeInUp">
                <div class="card-body">
                    <div class="row">
                        <hr class="hr hr-18 mb-4" />

                        <div class="col-8 mt-2">

                            <h2 class="card-title" id="#dish_name"> Pancakes</h2>
                        </div>
                        <div class="col-4">
                            <h4 class="mt-4 ar-green"><i class="fas fa-duotone fa-star "></i>&nbsp;200</h4>
                        </div>
                    </div>

                    <h5 class="card-subtitle mb-2 mt-2">Description</h5>
                    <p class="card-text" id="description_dish">Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                        Voluptatum, ipsam
                        officiis.</p>



                    <h5 class="card-subtitle mb-2 mt-2">Ingredients</h5>
                    <p class="card-text" id="ingredients_dish">Lorem ipsum dolor, sit amet consectetur adipisicing elit.
                        Voluptatum, ipsam
                        officiis.</p>
                    <a href="" class="noDecoration">
                        <div class="text-center">

                            {% if enable %}
                             <input type="submit" name="upload" onclick="" id="button" class="btn btn-primary" value="Vote" />

                            {% else %}
                             <input type="submit" name="upload" class="btn btn-primary" value="Vote" disabled/>

                            {% endif %}

                            <!-- <button class="btn text-center noDecoration mb-5">
                                Vote Now</button> -->
                        </div>

                    </a>

                </div>
            </div>
        </div>








    </div>


<!-- For Desktop & Laptop screens -->
    <div class="d-none d-lg-inline">
        <div class="">
            <div class="row m-5">
              
             <div class="col-6 p-5">
    
                <div class="m-5">
                    <img src="{{ BASIC_DIR }}/uploads/{{dish.d_Photo}}" alt="dish_img" style="width: 500px; height: 500px; left: 4rem; scale: 1;">
                </div>
                <!-- <ul class="thumb">
                  <li>
                    <span> <a href="" link="{{ BASIC_DIR }}/uploads/{{product.product_image1}}"  target="imgBox"> 
                      <img class="imgprop" src="{{ BASIC_DIR }}/uploads/{{product.product_image1}}" alt="">
                    </a> </span>
                  </li>
                </ul> -->

             </div>
    
             <div class="col-6">
              <div class="row">
                <span class="row" style="color: black; font-size: 1.5rem; font-weight: 500;">
                  {{dish.d_Name}}
                </span>
                <!-- <span class="row" style="color: #005C45; font-size:2rem; font-weight: 500;">
                  ₹ {{product.expected_price}}
                </span> -->
                <span class="row" style="font-size: 1.2rem; max-height: 90px; white-space: wrap; overflow: hidden; text-overflow: ellipsis;">
                  {{dish.d_Description}}
                </span>
                <h5 class="card-header" style="background-color: #a5fae5; color: black; font-weight: 600;">Ingredients</h5>
                <span class="row" style="font-size: 1.2rem; max-height: 90px; white-space: wrap; overflow: hidden; text-overflow: ellipsis;">
                  {{dish.d_Ingredients}}
                </span>

<!-- <a href="#" class="noDecoration"> -->
  <div class="text-center">
    <form method="post">
      {% csrf_token %}
      {% if enable %}
      <!-- <form method="post">
        {% csrf_token %} -->
       <button type="submit" name="upload" onclick="" id="button1" class="btn btn-primary" value="" > Vote </button>
      <!-- </form> -->
      {% else %}
      <!-- <form method="post">
        {% csrf_token %} -->
       <button type="submit" name="upload" class="btn btn-primary" value="" disabled> We Received Your Vote </button>
      <!-- </form> -->
      {% endif %}
    </form>
      <!-- <button class="btn text-center noDecoration mb-5">
          Vote Now</button> -->
  </div>

<!-- </a> -->
    
              </div>

              <!-- <div class="row" style="margin-top: 20px;">
                <div class="card" style="padding-left: 0; padding-right: 0;" >
                  <h5 class="card-header" style="background-color: #a5fae5; color: black; font-weight: 600;">Contact Details</h5>
                  <div class="card-body">
                    <h5 class="card-title">Name: {{seller_details.user_name}}</h5>
                    <h5 class="card-title">Email: {{seller_details.email}}</h5>
                    <h5 class="card-title">Mobile Number: {{seller_details.mobile_number}}</h5>
                  </div>
                </div>
              </div> -->
    
             </div>
    
    
            </div>
          </div>
    </div>





    <!-------javascript bundle----->
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3" crossorigin="anonymous">
    </script>

    <script src="https://code.jquery.com/jquery-3.6.1.min.js"
        integrity="sha256-o88AwQnZB+VDvE9tvIXrMQaPlFFSUTR+nldQm1LuPXQ=" crossorigin="anonymous"></script>
<script src="{% static 'js/preloader.js' %}"></script>


        <script>
          function onCdisable() {
  document.getElementById("button1").disabled = true;
}
        </script>


</body>

</html>